[mongodb]
mongodb.arohvya.online

[catalogue]
catalogue.arohvya.online

[frontend]
frontend.arohvya.online

[redis]
redis.arohvya.online

[user]
user.arohvya.online

[cart]
cart.arohvya.online

[mysql]
mysql.arohvya.online

[shipping]
shipping.arohvya.online

[rabbitmq]
rabbitmq.arohvya.online

[payment]
payment.arohvya.online

[dispatch]
dispatch.arohvya.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321