- name: Install MySQL server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySQL server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Setup root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
